/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DRouteImport } from './routes/d'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DIndexRouteImport } from './routes/d.index'
import { Route as DNewRouteImport } from './routes/d.new'
import { Route as CCompositionIdRouteImport } from './routes/c.$compositionId'
import { Route as BBrandSlugRouteImport } from './routes/b.$brandSlug'
import { Route as BBrandSlugIndexRouteImport } from './routes/b.$brandSlug.index'
import { Route as BBrandSlugGuidelinesRouteImport } from './routes/b.$brandSlug.guidelines'

const DRoute = DRouteImport.update({
  id: '/d',
  path: '/d',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DIndexRoute = DIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DRoute,
} as any)
const DNewRoute = DNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DRoute,
} as any)
const CCompositionIdRoute = CCompositionIdRouteImport.update({
  id: '/c/$compositionId',
  path: '/c/$compositionId',
  getParentRoute: () => rootRouteImport,
} as any)
const BBrandSlugRoute = BBrandSlugRouteImport.update({
  id: '/b/$brandSlug',
  path: '/b/$brandSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const BBrandSlugIndexRoute = BBrandSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BBrandSlugRoute,
} as any)
const BBrandSlugGuidelinesRoute = BBrandSlugGuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => BBrandSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/d': typeof DRouteWithChildren
  '/b/$brandSlug': typeof BBrandSlugRouteWithChildren
  '/c/$compositionId': typeof CCompositionIdRoute
  '/d/new': typeof DNewRoute
  '/d/': typeof DIndexRoute
  '/b/$brandSlug/guidelines': typeof BBrandSlugGuidelinesRoute
  '/b/$brandSlug/': typeof BBrandSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/c/$compositionId': typeof CCompositionIdRoute
  '/d/new': typeof DNewRoute
  '/d': typeof DIndexRoute
  '/b/$brandSlug/guidelines': typeof BBrandSlugGuidelinesRoute
  '/b/$brandSlug': typeof BBrandSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/d': typeof DRouteWithChildren
  '/b/$brandSlug': typeof BBrandSlugRouteWithChildren
  '/c/$compositionId': typeof CCompositionIdRoute
  '/d/new': typeof DNewRoute
  '/d/': typeof DIndexRoute
  '/b/$brandSlug/guidelines': typeof BBrandSlugGuidelinesRoute
  '/b/$brandSlug/': typeof BBrandSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/d'
    | '/b/$brandSlug'
    | '/c/$compositionId'
    | '/d/new'
    | '/d/'
    | '/b/$brandSlug/guidelines'
    | '/b/$brandSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/c/$compositionId'
    | '/d/new'
    | '/d'
    | '/b/$brandSlug/guidelines'
    | '/b/$brandSlug'
  id:
    | '__root__'
    | '/'
    | '/d'
    | '/b/$brandSlug'
    | '/c/$compositionId'
    | '/d/new'
    | '/d/'
    | '/b/$brandSlug/guidelines'
    | '/b/$brandSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DRoute: typeof DRouteWithChildren
  BBrandSlugRoute: typeof BBrandSlugRouteWithChildren
  CCompositionIdRoute: typeof CCompositionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/d': {
      id: '/d'
      path: '/d'
      fullPath: '/d'
      preLoaderRoute: typeof DRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/': {
      id: '/d/'
      path: '/'
      fullPath: '/d/'
      preLoaderRoute: typeof DIndexRouteImport
      parentRoute: typeof DRoute
    }
    '/d/new': {
      id: '/d/new'
      path: '/new'
      fullPath: '/d/new'
      preLoaderRoute: typeof DNewRouteImport
      parentRoute: typeof DRoute
    }
    '/c/$compositionId': {
      id: '/c/$compositionId'
      path: '/c/$compositionId'
      fullPath: '/c/$compositionId'
      preLoaderRoute: typeof CCompositionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$brandSlug': {
      id: '/b/$brandSlug'
      path: '/b/$brandSlug'
      fullPath: '/b/$brandSlug'
      preLoaderRoute: typeof BBrandSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$brandSlug/': {
      id: '/b/$brandSlug/'
      path: '/'
      fullPath: '/b/$brandSlug/'
      preLoaderRoute: typeof BBrandSlugIndexRouteImport
      parentRoute: typeof BBrandSlugRoute
    }
    '/b/$brandSlug/guidelines': {
      id: '/b/$brandSlug/guidelines'
      path: '/guidelines'
      fullPath: '/b/$brandSlug/guidelines'
      preLoaderRoute: typeof BBrandSlugGuidelinesRouteImport
      parentRoute: typeof BBrandSlugRoute
    }
  }
}

interface DRouteChildren {
  DNewRoute: typeof DNewRoute
  DIndexRoute: typeof DIndexRoute
}

const DRouteChildren: DRouteChildren = {
  DNewRoute: DNewRoute,
  DIndexRoute: DIndexRoute,
}

const DRouteWithChildren = DRoute._addFileChildren(DRouteChildren)

interface BBrandSlugRouteChildren {
  BBrandSlugGuidelinesRoute: typeof BBrandSlugGuidelinesRoute
  BBrandSlugIndexRoute: typeof BBrandSlugIndexRoute
}

const BBrandSlugRouteChildren: BBrandSlugRouteChildren = {
  BBrandSlugGuidelinesRoute: BBrandSlugGuidelinesRoute,
  BBrandSlugIndexRoute: BBrandSlugIndexRoute,
}

const BBrandSlugRouteWithChildren = BBrandSlugRoute._addFileChildren(
  BBrandSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DRoute: DRouteWithChildren,
  BBrandSlugRoute: BBrandSlugRouteWithChildren,
  CCompositionIdRoute: CCompositionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
