/* prettier-ignore-start */
/* eslint-disable */
// @ts-nocheck
//
// This file is normally GENERATED by @tanstack/router-plugin during `vite build`/`vite dev`.
// We commit a hand-written stub so typecheck passes before the first build.
// Run `pnpm --filter @framework/editor build` to regenerate from src/routes/.

import { Route as rootRoute } from './routes/__root'
import { Route as IndexRoute } from './routes/index'
import { Route as CompositionIdRoute } from './routes/c.$compositionId'

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { parentRoute: typeof rootRoute }
    '/c/$compositionId': { parentRoute: typeof rootRoute }
  }
}

const IndexRouteWithChildren = IndexRoute.update({ path: '/', getParentRoute: () => rootRoute })
const CompositionRouteWithChildren = CompositionIdRoute.update({
  path: '/c/$compositionId',
  getParentRoute: () => rootRoute,
})

export const routeTree = rootRoute.addChildren([
  IndexRouteWithChildren,
  CompositionRouteWithChildren,
])
