/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CCompositionIdRouteImport } from './routes/c.$compositionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CCompositionIdRoute = CCompositionIdRouteImport.update({
  id: '/c/$compositionId',
  path: '/c/$compositionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/c/$compositionId': typeof CCompositionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/c/$compositionId': typeof CCompositionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/c/$compositionId': typeof CCompositionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/c/$compositionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/c/$compositionId'
  id: '__root__' | '/' | '/c/$compositionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CCompositionIdRoute: typeof CCompositionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$compositionId': {
      id: '/c/$compositionId'
      path: '/c/$compositionId'
      fullPath: '/c/$compositionId'
      preLoaderRoute: typeof CCompositionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CCompositionIdRoute: CCompositionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
